ansible-container:
  image: "{{ builder_img_id }}"
  command: "ansible-playbook {% if params.debug %}-vvv{% endif %} -i /etc/ansible/inventory/hosts -c docker {{ params.ansible_options }} main.yml"
  environment:
    - DOCKER_HOST
    {% if env.DOCKER_TLS_VERIFY %}- DOCKER_TLS_VERIFY{% endif %}
    {% if env.DOCKER_CERT_PATH %}- DOCKER_CERT_PATH=/docker-certs/{% endif %}
    - COMPOSE_HTTP_TIMEOUT=3000
    - DOCKER_API_VERSION={{ api_version }}
  volumes:
    {% if env.DOCKER_CERT_PATH %}- $DOCKER_CERT_PATH:/docker-certs/{% endif %}
    - {{ base_path }}:/ansible-container/
  working_dir: /ansible-container/ansible/
{{ config }}
