FROM {{ item.0.base_image }}

# Uses shell module - should be two tasks
RUN {{ item.0.package_update_command }} && \
    {{ item.0.httpd_install_command }} && \
    chown -R {{ item.0.httpd_user }} {{ item.0.httpd_logdir }} && \
    mkdir -p {{ item.0.httpd_rundir }} && \
    chown -R {{ item.0.httpd_user }} {{ item.0.httpd_rundir }}

# Install dumb-init from URL - get_url module
ADD https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64 /usr/sbin/dumb-init

# Install httpd.conf - copy module
ADD {{ item.0.httpd_conf_src }} {{ item.0.httpd_conf_dest }}

# Install heartbeat page - unarchive module
ADD html.tar.gz {{ item.0.httpd_pageroot }}

# Install chaff - synchronize module
COPY foo /

# Uses command module
RUN ["chmod", "755", "/usr/sbin/dumb-init"]

# I am defaults
ARG apache_port=8000
ARG apache_pid_file={{ item.0.httpd_pid_file }}
ARG apache_run_user={{ item.0.httpd_user }}
ARG apache_run_group={{ item.0.httpd_run_group }}
ARG apache_log_dir={{ item.0.httpd_logdir }}
ARG apache_lock_dir={{ item.0.httpd_lock_dir }}
ENV APACHE_PORT=${apache_port}
ENV APACHE_PID_FILE=${apache_pid_file}
ENV APACHE_RUN_USER=${apache_run_user}
ENV APACHE_RUN_GROUP=${apache_run_group}
ENV APACHE_LOG_DIR=${apache_log_dir}
ENV APACHE_LOCK_DIR=${apache_lock_dir}

# Single label
LABEL a=1
# Multiple labels
LABEL b=2 c=3
# Quoted keys and values
LABEL "the bird"="the word"
# Multi-line
LABEL foo=bar \
      baz=buzz

# I am metadata
CMD ["{{ item.0.httpd_bin }}", "-DFOREGROUND"]
ENTRYPOINT ["/usr/sbin/dumb-init"]
EXPOSE $apache_port
USER {{ item.0.httpd_user }}
VOLUME ["/vol"]
WORKDIR /tmp
SHELL ["/bin/sh", "-c"]

# Should be run using shell module as {{ item.0.httpd_user }} in /tmp explicitly using /bin/sh -c
# RUN /bin/true

